### ISSUE TITLE
atcoder-rust-base needs to be broken as a project for cargo-generate

### ISSUE THREAD

**Issue by qryxip** [rust-lang-ja/atcoder-rust-base#53]
jaブランチにマージするときに忘れないように書いておきます。

cargo-generateはCargo.tomlをTOMLとしてパースせずに[liquid](https://crates.io/crates/liquid)でテンプレートを展開します。なので

```toml
[package]
name = "{{project-name}}"
```

とする必要がありますが当然packageとして壊れることになります。

あとcargo-generate.tomlの指定も効いてないっぽいです。 (ディレクトリではなくきちんとワイルドカードで指定する必要がある)
